create table PRODUTOS(
	ID INTEGER IDENTITY(1,1),
	NOME VARCHAR (MAX),
	VALOR INTEGER,
	CONSTRAINT PK_PRODUTOS PRIMARY KEY(ID),
)
CREATE TABLE CLIENTE(
	ID INTEGER IDENTITY(1,1),
	NOME VARCHAR (MAX),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
)
CREATE TABLE PEDIDO
(
	ID INTEGER IDENTITY (1,1),
	IDCLIENTE INTEGER,
	QUANTIDADE INTEGER,
	DATA DATETIME,
	CONSTRAINT PK_PEDIDO PRIMARY KEY(ID),
	CONSTRAINT FK_PEDIDOIDCLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(ID),
)
CREATE TABLE PedidoItem
(
	ID INTEGER IDENTITY(1,1),
	ID_PEDIDO INTEGER,
	ID_PRODUTOS INTEGER,
	CONSTRAINT PK_PEDIDO_ITEM PRIMARY KEY(ID),
	CONSTRAINT FK_PedidoItemIdPedido FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID),
	CONSTRAINT FK_PedidoItemIdProdutos FOREIGN KEY (ID_PRODUTOS) REFERENCES PRODUTOS(ID)
)

drop table PEDIDO_ITEM